quarkus.index-dependency.jms.enabled=false
quarkus.index-dependency.artemis.enabled=false
quarkus.index-dependency.spring.enabled=false
quarkus.index-dependency.ant.enabled=false
quarkus.index-dependency.logwriting.enabled=false

quarkus.arc.remove-unused-beans=jms,artemis,spring,ant
quarkus.arc.remove-unused-beans=jms,artemis,spring,ant
quarkus.log.category."org.jgroups".level=WARN
quarkus.log.category."io.quarkus.dep.index".level=ERROR